V1.1.x issue 98
akka/akka-persistence-dynamodb-1.x pull request #100
Opened 2021-10-13 18:17 UTC by spangaer

#98 

Hi, I'd actually like to submit this pull request against a 1.1.x version. So it could potentially be released as 1.1.2.

If there's interest and there's an intention of releasing an actual 1.2.0. I guess we can look in to porting to that too.

Any feedback is welcome.

For a more detailed explanation on how things are fixed please read here:
https://github.com/akka/akka-persistence-dynamodb/issues/98#issuecomment-942578725

2021-10-13 18:17 UTC, lightbend-cla-validator commented
Hi @spangaer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

2021-10-15 06:46 UTC, coreyoconnor requested changes
Thanks!
Only minor changes request. Adding the "high-distrust" fixes option is great. Nice touch!

Once the nitpicks are fixed and I've considered this a bit more (while fixing CI) I'll approve and merge. :)

2021-10-15 06:46 UTC, coreyoconnor commented on .gitignore
> +.metals
needs newline at end of file

2021-10-15 06:46 UTC, coreyoconnor commented on .scalariform.conf
> +autoformat=false
remove file from PR

2021-10-15 06:46 UTC, coreyoconnor commented on .vscode/settings.json
> +{
remove file from PR

2021-10-15 06:46 UTC, coreyoconnor commented on project/Publish.scala
> +    defaultPublishTo := crossTarget.value / "repository")
remove change from PR? Or is this no longer required with the updated sbt-pgp plugin?

2021-10-15 06:46 UTC, coreyoconnor commented on project/esko.sbt
> +addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.6")
remove file from PR

2021-10-15 09:21 UTC, spangaer commented on .scalariform.conf
> +autoformat=false
I agree that it shouldn't be there. But compilation will trigger a set of formats without. Because of the Scalariform that needed to be upgraded to 1.8.0. (that was the one available on maven central)

2021-10-15 09:29 UTC, spangaer commented on project/Publish.scala
> +    defaultPublishTo := crossTarget.value / "repository")
TBH I don't know. I just made an effort to make it build. I haven't actually done PGP signed publishes.

This part specifically I stumbled on in this commit:
https://github.com/akka/akka-persistence-dynamodb/commit/0192e14b25ac82de05541417e26b6db33aa4f8f8

So it looks like it can do without.

2021-10-15 09:38 UTC, lightbend-cla-validator commented
Hi @spangaer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

2021-10-15 09:46 UTC, spangaer commented
On the subject of the CLA, I'm looking in to that. I was waiting for a bit to see if the PR was going to be picked up.

I'll get it taken care of ASAP, but I need to pick up it up internally. I know I'm not out of my jurisdiction by simply pushing it to a public repo, but the CLA adds an extra level. (but I understand that's where copyright history has landed us)

2021-12-05 07:27 UTC, coreyoconnor approved these changes
LGTM tho you should wait until I fix CI to merge in master.

Also update the test to use `IntegSpec. This incorporates the container based DynamoDB testing.

* https://github.com/akka/akka-persistence-dynamodb/blob/master/src/test/scala/akka/persistence/dynamodb/IntegSpec.scala
*

2021-12-22 19:37 UTC, spangaer commented
I haven't forgotten about this. Still waiting for the legal department...
It'll get there, eventually...

2022-02-07 10:41 UTC, spangaer commented
CLA part fixed.

2022-02-09 10:49 UTC, spangaer commented
@lightbend-cla-validator  please check again

2022-02-09 17:53 UTC, coreyoconnor commented
Hi @spangaer thanks for poking the CLA bot.
Github is reporting merge conflicts. Are you able to resolve those?

2022-02-17 01:41 UTC, merged

2022-03-03 12:40 UTC, jvce commented
Hi

Any idea when a new release would be made including this fix?

2022-09-18 17:21 UTC, coreyoconnor commented
@jvce This was included in `1.1.2` and will be included in the pending `1.3.0`