sbt-scalariform 1.8.2
akka/akka-persistence-dynamodb-1.x pull request #73
Opened 2018-02-11 00:47 UTC by sullis

2018-02-13 00:14 UTC, sullis commented
ping @johanandren  @raboof

2018-02-13 08:19 UTC, johanandren approved these changes
LGTM i guess

2018-02-13 11:54 UTC, raboof commented on src/test/scala/akka/persistence/dynamodb/snapshot/DynamoDBUtils.scala
> +      new KeySchemaElement().withAttributeName(SequenceNr).withKeyType(KeyType.RANGE))
I kind of liked these newlines before 'dangling' parenthesis, can we configure scalariform to keep them? Otherwise LGTM.

2018-03-12 10:21 UTC, raboof requested changes

2018-03-12 10:21 UTC, raboof commented on src/test/scala/akka/persistence/dynamodb/journal/DynamoDBIntegrationLoadSpec.scala
> +      view ! Update(await     = true, replayMax = 3L)
The additional whitespace here (and below) doesn't look right

2018-03-12 10:22 UTC, raboof commented
@sullis can you fix the whitespace issues?

2019-06-26 14:38 UTC, teroxik commented
@sullis do you plan to address the changes or not? If not I I will look into getting this in.

2019-07-13 20:15 UTC, teroxik commented
Ok, closing this and will move to scalafmt with same settings as akka project has.

2019-07-13 20:15 UTC, closed without merging